### ISSUE TITLE
"ycb_large.json" file is missing 

### ISSUE THREAD

**Issue by ronen85** [liruiw/GA-DDPG#1]
Hello, 
While trying to run the example:
`bash experiments/scripts/test_demo.sh`
I get the following error:
```
+ set -e
+++ dirname -- experiments/scripts/test_demo.sh
++ cd experiments/scripts
++ pwd
+ DIR=/home/nir1tv/projects/GA-DDPG/experiments/scripts
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ LOG_NAME=agent
+ LOG=output//log.txt
+ MODEL_NAME=dummy
+ RUN_NUM=3
+ EPI_NUM=165
+ EPOCH=latest
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=outputs/dummy/test_log.txt.2021-07-14_10-39-15
+ exec
++ tee -a outputs/dummy/test_log.txt.2021-07-14_10-39-15
tee: outputs/dummy/test_log.txt.2021-07-14_10-39-15: No such file or directory
+ echo Logging output to outputs/dummy/test_log.txt.2021-07-14_10-39-15
Logging output to outputs/dummy/test_log.txt.2021-07-14_10-39-15
+ python -m core.train_test_offline --expert --pretrained output/demo_model --test --render
pybullet build time: Jul 14 2021 10:11:29
Output will be saved to `output/demo_model`
Using config:
{'DATA_ROOT_DIR': 'data/scenes',
 'EPOCHS': 200,
.....
.....
Let's use 2 GPUs!
schedule: [8000, 16000, 30000, 50000, 70000, 90000]
schedule: [8000, 16000, 30000, 50000, 70000, 90000]
Output will be saved to `output/demo_model`
video output: YCB_td3_critic_aux_policy_aux.yaml stat output: rollout_success.script_td3_critic_aux_policy_aux.yaml.txt
load pretrained policy!!!!
load pretrained critic!!!!
load feat optim
load pretrained feature!!!! from: output/demo_model/DDPG_state_feat_PandaYCBEnv_latest step :249921
output_time: demo_model logdir: output/demo_model/PandaYCBEnv_DDPG
Traceback (most recent call last):
  File "/home/nir1tv/miniconda3/envs/gaux/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nir1tv/miniconda3/envs/gaux/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nir1tv/projects/GA-DDPG/core/train_test_offline.py", line 371, in <module>
    with open(file) as f: file_dir = json.load(f)
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/object_index/ycb_large.json'
```
Note that I have executed all of the `download_*` sh scripts from `./experiments/script` folder.

Cheers,
Ronen.

**Comment by liruiw** [comment]
Sorry, I just added the object index file!
